/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.grozeille.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Document extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Document\",\"namespace\":\"org.grozeille.avro\",\"fields\":[{\"name\":\"path\",\"type\":\"string\"},{\"name\":\"lang\",\"type\":\"string\"},{\"name\":\"body\",\"type\":{\"type\":\"bytes\",\"java-class\":\"[B\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence path;
  @Deprecated public java.lang.CharSequence lang;
  @Deprecated public java.nio.ByteBuffer body;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Document() {}

  /**
   * All-args constructor.
   */
  public Document(java.lang.CharSequence path, java.lang.CharSequence lang, java.nio.ByteBuffer body) {
    this.path = path;
    this.lang = lang;
    this.body = body;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return path;
    case 1: return lang;
    case 2: return body;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: path = (java.lang.CharSequence)value$; break;
    case 1: lang = (java.lang.CharSequence)value$; break;
    case 2: body = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'path' field.
   */
  public java.lang.CharSequence getPath() {
    return path;
  }

  /**
   * Sets the value of the 'path' field.
   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /**
   * Gets the value of the 'lang' field.
   */
  public java.lang.CharSequence getLang() {
    return lang;
  }

  /**
   * Sets the value of the 'lang' field.
   * @param value the value to set.
   */
  public void setLang(java.lang.CharSequence value) {
    this.lang = value;
  }

  /**
   * Gets the value of the 'body' field.
   */
  public java.nio.ByteBuffer getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.nio.ByteBuffer value) {
    this.body = value;
  }

  /** Creates a new Document RecordBuilder */
  public static org.grozeille.avro.Document.Builder newBuilder() {
    return new org.grozeille.avro.Document.Builder();
  }
  
  /** Creates a new Document RecordBuilder by copying an existing Builder */
  public static org.grozeille.avro.Document.Builder newBuilder(org.grozeille.avro.Document.Builder other) {
    return new org.grozeille.avro.Document.Builder(other);
  }
  
  /** Creates a new Document RecordBuilder by copying an existing Document instance */
  public static org.grozeille.avro.Document.Builder newBuilder(org.grozeille.avro.Document other) {
    return new org.grozeille.avro.Document.Builder(other);
  }
  
  /**
   * RecordBuilder for Document instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Document>
    implements org.apache.avro.data.RecordBuilder<Document> {

    private java.lang.CharSequence path;
    private java.lang.CharSequence lang;
    private java.nio.ByteBuffer body;

    /** Creates a new Builder */
    private Builder() {
      super(org.grozeille.avro.Document.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.grozeille.avro.Document.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.path)) {
        this.path = data().deepCopy(fields()[0].schema(), other.path);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lang)) {
        this.lang = data().deepCopy(fields()[1].schema(), other.lang);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body)) {
        this.body = data().deepCopy(fields()[2].schema(), other.body);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Document instance */
    private Builder(org.grozeille.avro.Document other) {
            super(org.grozeille.avro.Document.SCHEMA$);
      if (isValidValue(fields()[0], other.path)) {
        this.path = data().deepCopy(fields()[0].schema(), other.path);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lang)) {
        this.lang = data().deepCopy(fields()[1].schema(), other.lang);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body)) {
        this.body = data().deepCopy(fields()[2].schema(), other.body);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'path' field */
    public java.lang.CharSequence getPath() {
      return path;
    }
    
    /** Sets the value of the 'path' field */
    public org.grozeille.avro.Document.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.path = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'path' field has been set */
    public boolean hasPath() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'path' field */
    public org.grozeille.avro.Document.Builder clearPath() {
      path = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'lang' field */
    public java.lang.CharSequence getLang() {
      return lang;
    }
    
    /** Sets the value of the 'lang' field */
    public org.grozeille.avro.Document.Builder setLang(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lang = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'lang' field has been set */
    public boolean hasLang() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'lang' field */
    public org.grozeille.avro.Document.Builder clearLang() {
      lang = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'body' field */
    public java.nio.ByteBuffer getBody() {
      return body;
    }
    
    /** Sets the value of the 'body' field */
    public org.grozeille.avro.Document.Builder setBody(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.body = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'body' field has been set */
    public boolean hasBody() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'body' field */
    public org.grozeille.avro.Document.Builder clearBody() {
      body = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Document build() {
      try {
        Document record = new Document();
        record.path = fieldSetFlags()[0] ? this.path : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lang = fieldSetFlags()[1] ? this.lang : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.body = fieldSetFlags()[2] ? this.body : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
